Integrate zephyr can
spacecubics/libcsp pull request #1
Opened 2023-08-03 08:00 UTC by sasataku

This PR is integrated the zephyr can driver to libcsp.

We prepare the sample code for server/client test.
In this sample code, we use CSP version1 because our CubeSat use CSP version1.

I've tested on real board as below.

Server:
```shell
*** Booting Zephyr OS build zephyr-v3.4.0-1710-g85059866d5f4 ***
Initialising CSP
INIT CAN0: device: [can@40400000], bitrate: 1000000, promisc: 0
Connection table
[00 0xdc10] S:0, 0 -> 56360, 0 -> 0 (17) fl 0
[01 0xdce4] S:0, 0 -> 1000, 0 -> 0 (18) fl 0
[02 0xddb8] S:0, 0 -> 1000, 0 -> 0 (19) fl 0
[03 0xde8c] S:0, 0 -> 1000, 0 -> 0 (20) fl 0
[04 0xdf60] S:0, 0 -> 1000, 0 -> 0 (21) fl 0
[05 0xe034] S:0, 0 -> 1000, 0 -> 0 (22) fl 0
[06 0xe108] S:0, 0 -> 1000, 0 -> 0 (23) fl 0
[07 0xe1dc] S:0, 0 -> 1000, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 5 mtu: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

CAN0       addr: 10 netmask: 0 mtu: 248
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Route table
0/0 CAN0
Server task started
Packet received on MY_SERVER_PORT: Hello World (1)
Packet received on MY_SERVER_PORT: Hello World (2)
Packet received on MY_SERVER_PORT: Hello World (3)
``` 

Client:
```shell
*** Booting Zephyr OS build zephyr-v3.4.0-1710-g85059866d5f4 ***
Initialising CSP
INIT CAN0: device: [can@40400000], bitrate: 1000000, promisc: 0
Connection table
[00 0xdc10] S:0, 20 -> 0, 17 -> 1 (17) fl 0
[01 0xdce4] S:0, 20 -> 0, 18 -> 4 (18) fl 0
[02 0xddb8] S:0, 20 -> 0, 19 -> 10 (19) fl 0
[03 0xde8c] S:0, 20 -> 0, 20 -> 1 (20) fl 0
[04 0xdf60] S:0, 20 -> 0, 21 -> 4 (21) fl 0
[05 0xe034] S:0, 20 -> 0, 22 -> 10 (22) fl 0
[06 0xe108] S:0, 20 -> 0, 23 -> 4 (23) fl 0
[07 0xe1dc] S:0, 20 -> 0, 24 -> 10 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 5 mtu: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

CAN0       addr: 10 netmask: 0 mtu: 248
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Route table
0/0 CAN0
Client task started
Ping address: 20, result 11 [mS]
reboot system request sent to address: 20
Ping address: 20, result 13 [mS]
reboot system request sent to address: 20
Ping address: 20, result 12 [mS]
reboot system request sent to address: 20
Ping address: 20, result 16 [mS]
```

2023-08-03 08:04 UTC, yashi commented
It's PICOLIBC not "PICOLIB"

2023-08-03 09:00 UTC, yashi commented on contrib/zephyr/samples/server-client/main.c
> +#if CONFIG_CSP_HAVE_CAN
let's use `IS_ENABLED()`.  We don't use it in libcsp but this code is Zephyr only.

ref) https://github.com/libcsp/libcsp/pull/219

2023-08-03 09:05 UTC, yashi commented
> This PR is integrated the zephyr can driver to libcsp.

Some suggestions:

- This PR is integrating the zephyr CAN driver to libcsp.
- This PR integrates the zephyr CAN driver to libcsp.
- This PR adds a new CAN driver for Zephyr.

2023-08-05 07:59 UTC, yashi requested changes

2023-08-05 07:59 UTC, yashi commented on src/drivers/CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "Zephyr" AND CONFIG_CAN)
Ah, I don't think we can use `CONFIG_` in `CMakeLists.txt` because we also supports `cmake` build for non-Zephyr.   hmm..... I'm not sure what is the best way around.

2023-08-21 11:21 UTC, sasataku commented on contrib/zephyr/Kconfig
>  endif # LIBCSP
Thanks.
Will replace commit log.

2023-08-21 11:29 UTC, sasataku commented on contrib/zephyr/samples/server-client/main.c
Yes, that's right..
Will fix it.

2023-08-21 11:35 UTC, sasataku commented on contrib/zephyr/samples/server-client/main.c
Thank you for your explanation
Will update commit log.

2023-08-22 06:17 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +#include <unistd.h>
Removed.

2023-08-22 09:14 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		/* Call RX callbacsp_can_rx_frameck */
oops..
FIxed.

2023-08-22 09:23 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +static void disable_can(can_context_t * pctx) {
Okay.
Removed hungarian notation.

2023-08-22 09:31 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +static void can_rx_thread(can_context_t * pctx, void *, void *) {
Thanks.
Fixed.

2023-08-22 09:45 UTC, sasataku commented on contrib/zephyr/samples/server-client/main.c
> +#if CONFIG_CSP_HAVE_CAN
OKay. 
Replace to `IS_ENABLED()`.

2023-08-22 10:12 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +static K_THREAD_STACK_DEFINE(rx_stack, STACKSIZE);
Moved to Kconfig.

2023-08-22 10:21 UTC, sasataku commented on contrib/zephyr/samples/server-client/csp_server_client_zephyr.c
Thanks. Fixed.

2023-08-22 10:33 UTC, sasataku commented on contrib/zephyr/samples/arch/prj.conf
>  CONFIG_MINIMAL_LIBC_RAND=y
Removed.

2023-08-23 04:18 UTC, sasataku commented on contrib/zephyr/CMakeLists.txt
> -  set(CSP_PRINT_STDIO OFF)
Fixed the Commit log.

And about `Zephyr logging interface`.
I understand your opinion, but it's a significant task. Therefore, I will create a new ticket and work on these tasks.

https://github.com/spacecubics/libcsp/issues/2

2023-08-23 04:20 UTC, sasataku commented on contrib/zephyr/samples/server-client/main.c
> +	csp_conf.version = 1;
OKay. removed this code.

2023-08-23 07:18 UTC, sasataku commented on src/interfaces/CMakeLists.txt
> +  (CMAKE_SYSTEM_NAME STREQUAL "Zephyr" AND CONFIG_CAN))
Thinking about it again, the interface source code is built regardless of the configuration on other OSes, so I will stop adding conditions.

2023-08-24 00:10 UTC, yashi requested changes

2023-08-28 04:13 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		return CSP_ERR_INVAL;
So many return codes are described in this API. 
I will modify it to use 'goto'.

2023-08-28 05:43 UTC, sasataku commented on src/drivers/CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "Zephyr" AND CONFIG_CAN)
We discussed and decided to use the CONFIG_CAN under `contribute/zephyr` in the CMakefile.
We will set it to ON for the variable and under `src/drivers`, we will use that variable for evaluation.

2023-08-28 05:49 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +static K_THREAD_STACK_DEFINE(rx_stack, STACKSIZE);
ANd we had a discussion and agreed to use "CSP_CAN_XX" as a common prefix.

2023-08-28 06:47 UTC, sasataku commented on contrib/zephyr/CMakeLists.txt
> -  set(CSP_PRINT_STDIO OFF)
Yes, I misunderstood about the stdio with minimal libc and piclibc.
And as a result of offline discussion, we will use the `LOG_*()` on CSP CAN driver and sample code instead of `csp_print()`.

2023-10-02 11:42 UTC, sasataku commented on contrib/zephyr/Kconfig
> +	default 0
This RX thread should process CAN frames passed from the CAN driver with higher priority than other application threads that use libcsp.
So will change to `-1` as cooperative thread.

2023-10-03 03:16 UTC, sasataku commented
@yashi 

I've rebasing this PR based on latest develop branch (hash: c904ba) and fixed the code by all review comment.
Could you check this PR again ?

## Linux ->  Zephyr
### Client (Linux)
```
$ ./build/examples/csp_server_client -a 20 -r 10 -c can0
Initialising CSPINIT CAN: device: [can0], bitrate: 1000000, promisc: 1
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
Connection table
[00 0x55a7ec13f8a0] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x55a7ec13f9b0] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x55a7ec13fac0] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x55a7ec13fbd0] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x55a7ec13fce0] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x55a7ec13fdf0] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x55a7ec13ff00] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x55a7ec140010] S:0, 0 -> 0, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 14 dfl: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

CAN        addr: 20 netmask: 0 dfl: 1
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Client task startedPing address: 10, result 8 [mS]
reboot system request sent to address: 10
Ping address: 10, result 8 [mS]
reboot system request sent to address: 10
Ping address: 10, result 8 [mS]
reboot system request sent to address: 10
Ping address: 10, result 8 [mS]
reboot system request sent to address: 10
Ping address: 10, result 8 [mS]
reboot system request sent to address: 10
```
### Server (Zephyr)
```
*** Booting Zephyr OS build v3.5.0-rc1-10-ga178aa9855bd ***
[00:00:00.000,000] <inf> csp_sample_server_client: Initialising CSP
[00:00:00.001,000] <inf> csp_sample_server_client: Connection table
[00:00:00.001,000] <inf> csp_sample_server_client: Server task started
[00:00:05.518,000] <inf> csp_sample_server_client: Packet received on MY_SERVER_PORT: Hello world A
[00:00:06.527,000] <inf> csp_sample_server_client: Packet received on MY_SERVER_PORT: Hello world B
[00:00:07.536,000] <inf> csp_sample_server_client: Packet received on MY_SERVER_PORT: Hello world C
[00:00:08.546,000] <inf> csp_sample_server_client: Packet received on MY_SERVER_PORT: Hello world D
[00:00:09.555,000] <inf> csp_sample_server_client: Packet received on MY_SERVER_PORT: Hello world E
```

## Zephyr -> Linux
### Client (Zephyr)
```
*** Booting Zephyr OS build v3.5.0-rc1-10-ga178aa9855bd ***
[00:00:00.000,000] <inf> csp_sample_server_client: Initialising CSP
[00:00:00.001,000] <inf> csp_sample_server_client: Connection table
[00:00:00.001,000] <inf> csp_sample_server_client: Client task started
[00:00:01.010,000] <inf> csp_sample_server_client: Ping address: 20, result 8 [mS]
[00:00:01.011,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:02.021,000] <inf> csp_sample_server_client: Ping address: 20, result 9 [mS]
[00:00:02.021,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:03.030,000] <inf> csp_sample_server_client: Ping address: 20, result 8 [mS]
[00:00:03.031,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:04.041,000] <inf> csp_sample_server_client: Ping address: 20, result 9 [mS]
[00:00:04.042,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:05.051,000] <inf> csp_sample_server_client: Ping address: 20, result 8 [mS]
[00:00:05.052,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:06.061,000] <inf> csp_sample_server_client: Ping address: 20, result 8 [mS]
[00:00:06.062,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:07.071,000] <inf> csp_sample_server_client: Ping address: 20, result 8 [mS]
[00:00:07.072,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
[00:00:08.081,000] <inf> csp_sample_server_client: Ping address: 20, result 8 [mS]
[00:00:08.082,000] <inf> csp_sample_server_client: reboot system request sent to address: 20
```

### Server (Linux)
```
$ ./build/examples/csp_server_client -a 20  -c can0
Initialising CSPINIT CAN: device: [can0], bitrate: 1000000, promisc: 1
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
Connection table
[00 0x562bc41298a0] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x562bc41299b0] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x562bc4129ac0] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x562bc4129bd0] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x562bc4129ce0] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x562bc4129df0] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x562bc4129f00] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x562bc412a010] S:0, 0 -> 0, 0 -> 0 (24) fl 0
Interfaces
LOOP       addr: 0 netmask: 14 dfl: 0
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

CAN        addr: 20 netmask: 0 dfl: 1
           tx: 00000 rx: 00000 txe: 00000 rxe: 00000
           drop: 00000 autherr: 00000 frame: 00000
           txb: 0 (0B) rxb: 0 (0B) 

Server task started
Packet received on MY_SERVER_PORT: Hello world A
Packet received on MY_SERVER_PORT: Hello world B
Packet received on MY_SERVER_PORT: Hello world C
Packet received on MY_SERVER_PORT: Hello world D
Packet received on MY_SERVER_PORT: Hello world E
Packet received on MY_SERVER_PORT: Hello world F
Packet received on MY_SERVER_PORT: Hello world G
Packet received on MY_SERVER_PORT: Hello world H
Packet received on MY_SERVER_PORT: Hello world I
```

2023-10-04 02:32 UTC, yashi commented
Why do you have commits from other guys?

2023-10-04 02:40 UTC, sasataku commented
> Why do you have commits from other guys?

I'm sorry, it seems I made a mistake with the rebase operation. I will fix it.

2023-10-04 04:36 UTC, yashi requested changes

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +		/* Drop remote frames */
Please write "why".

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +		ret = k_msgq_get(&csp_msgq, &frame, K_FOREVER);
Don't you need to set timeout?

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +		.id = CFP_MAKE_DST(ctx->iface.addr),
Why is it OK to use `CFP_MAKE_DST()` here without version check?

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +	filter_id = can_add_rx_filter_msgq(ctx->device, &csp_msgq, &filter);
Just curious, how can we unset promisc mode? don't you need the `filter_id` when we disable promiscuous mode?

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +	if (ret != 0) {
Let's make all error check to
```c
if (ret < 0) {
```

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +		ret = CSP_ERR_DRIVER;
I don't like `CSP_ERR_DRIVER`.  Please return `ret` as is.

This wrapper function will go away anyway.  I think it's a layer violation to call interface layer from driver layer.

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +	/* Set filter mode */
Do we have mode for filter?

2023-10-04 04:36 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +static void can_rx_thread(void * arg1, void * arg2, void * arg3) {
Can we keep `can_` prefix for underlaying OSes (Linux, Zephyr).  And make libcsp to use `csp_can_` prefix?

2023-10-04 04:37 UTC, yashi reviewed
> This commit supports the CAN interface as physical layer for CSP.

I don't quite get what you mean.

2023-10-04 09:26 UTC, sasataku commented on contrib/zephyr/CMakeLists.txt
> +    set(CSP_USE_RTABLE OFF)
Thanks. will remove.

2023-10-04 09:40 UTC, sasataku commented on contrib/zephyr/samples/server-client/main.c
> +	if (!default_iface) {
Okay. will add the reference.

2023-10-04 09:51 UTC, sasataku commented on contrib/zephyr/samples/server-client/main.c
> +	csp_print("Interfaces");
I forgot to replace it.
'csp_print()' remained in other places, so will replace it with 'LOG_()'

2023-10-04 10:08 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	if (ret != 0) {
OKay. will fix it.

2023-10-04 10:16 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +static void can_rx_thread(void * arg1, void * arg2, void * arg3) {
I agree with your suggestion. we should unify to use `csp_can _` prefix.

2023-10-04 10:31 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +			LOG_ERR("%s[%s]: k_msgq_get() failed, errno %d\n", __FUNCTION__, ctx->name, ret);
I left the `\n` when I used `csp_print()`, will remove it entirely

2023-10-04 10:33 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +			LOG_ERR("%s[%s]: k_msgq_get() failed, errno %d\n", __FUNCTION__, ctx->name, ret);
As you said,function names is too much information, will remove it.

2023-10-04 10:57 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		/* Drop remote frames */
Wil change the comment to `CSP uses data frame only, drop it.`

2023-10-04 11:23 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	/* Set filter mode */
No, we don't have mode of filter.
This commit message was copied from can_socketcan.c.
Will fix it.

2023-10-04 11:27 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		ret = CSP_ERR_DRIVER;
Okay, return `ret` as is.

2023-10-04 11:36 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	ret = can_start(ctx->device);
It's too early to start CAN before adding the RX filter. Will change the order.

2023-10-11 02:36 UTC, sasataku commented on include/csp/drivers/can_zephyr.h
> +*/
Okay.

2023-10-11 02:39 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		.id = CFP_MAKE_DST(ctx->iface.addr),
Yes,  as you said,we should be check the version.
However this code is already removed.

2023-10-11 02:41 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	filter_id = can_add_rx_filter_msgq(ctx->device, &csp_msgq, &filter);
As you said, in the current implementation, we can not unset promisc mode.
After discussions, we decided to allow the user to set the address and mask for the RX filter.

2023-10-17 05:02 UTC, yashi requested changes

2023-10-17 05:02 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +			break;
What should we do when this condition hit on our satellite?

2023-10-17 05:16 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	struct k_thread rx_thread;;
Fixed.

2023-10-17 05:19 UTC, sasataku commented on contrib/zephyr/Kconfig
> +	int "RX Thread number in the CSP CAN Driver"
Thanks. Fixed

2023-10-17 05:33 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +			LOG_ERR("[%s] discarding Standard ID frame", iface->name);
Yes, we will continue processing RX frame.
So should be use `LOG_WRN()`.

2023-10-17 05:35 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +			LOG_ERR("[%s] discarding RTR frame", iface->name);
Fixed.

2023-10-17 05:38 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		LOG_ERR("[%s] k_calloc() failed. %d byte", ifname, sizeof(can_context_t));
Fixed.

2023-10-17 05:40 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		LOG_ERR("[%s] No more RX thread can be created. (MAX: %d) Please check CSP_CAN_RX_THREAD_NUM.",
Okay. I missed add the `CONFIG_` prefix. Will fix.

2023-10-17 06:19 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +			break;
Basically, this case is an abnormal route. Therefore, I think it is better to exit the thread.
However user application should be know the `RX thread is exited`.

This is just idea for know the RX thread status by user.
 - Use `k_thread_join` with k_thread struct in CAN context.
- RX thread uses a condition variable.-

2023-10-17 06:21 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	can_context_t * ctx = NULL;
Ah. It's intentional, if we have no left the free number of thread stacks, no call `k_callock`.

2023-10-17 06:43 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		ifname = device->name;
Okay. Will check it.

2023-10-17 06:43 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		ifname = device->name;
In this function, it use `strncpy` to copy only up to CSP_IFLIST_NAME_MAX - 1.
And this interface name is basically used only for debug print.

2023-10-17 06:46 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		ifname = device->name;
Agree. Will change the setting process of interface naming.

2023-10-17 08:36 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +		goto end;
Yes, I have many memory leaks..
Will fix it.

2023-10-17 08:37 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +end:
Will create the `nofree` and `free` target for handle the clean up memory.

2023-10-17 08:48 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +int csp_can_set_rx_filter(csp_iface_t * iface, uint16_t filter_addr, uint16_t filter_mask) {
Fixed

2023-10-17 10:15 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	bool need_to_stop_rx;
Thanks!
I didn't know Zephyr's Event. it's useful.

2023-10-19 23:53 UTC, yashi requested changes

2023-10-19 23:53 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +	(void)csp_can_remove_interface(&ctx->iface);
Do not touch `ctx` after free.

2023-10-20 00:21 UTC, yashi commented on src/drivers/can/can_zephyr.c
> +	}
I'd write:
```c
if ((iface == NULL) || (iface->driver_data == NULL)) {
    ret = CSP_ERR_INVAL;
    goto end;
}

ctx = iface->driver_data;
```

A good point of this is that the `if` block indicates and gives readers a visual cue about the argument checking.  And after the block, we resume nominal computation (assigning ctx, etc.).

Just in case you don't know, because evaluation of logical-and `&&` and logical-or `||` in C is [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation), it is guaranteed to stop evaluating after `iface == NULL` is evaluated `true` with `||`.

2023-10-20 00:54 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	(void)csp_can_remove_interface(&ctx->iface);
Opps.. Fixed.

2023-10-20 01:01 UTC, sasataku commented on src/drivers/can/can_zephyr.c
> +	}
Thanks.
I misunderstood that both condition is evaluated.
Fixed.

2023-11-04 14:40 UTC, yashi commented
merged upstream.

2023-11-04 14:40 UTC, closed without merging